[package]
name = "AoC"
version = "0.1.0"
edition = "2021"
jemalloc = false

[dependencies]
colored = "2.1.0"
itertools = "0.13.0"
petgraph = "0.6.5"

[profile.release]
debug = true
debuginfo-level = 2
opt-level = 3
